import {
  Image,
  Maximize2,
  Minimize2,
  Crop,
  RotateCw,
  RotateCcw,
  FlipHorizontal2,
  Contrast,
  Aperture,
  Stamp,
  Tags,
  SlidersHorizontal,
  Eraser,
  Files,
  Scissors,
  FileMinus,
  FileImage,
  ListOrdered,
  Droplets,
  FileText,
  Images,
  Download,
  Youtube,
  Music,
  QrCode,
  Braces,
  Hash,
  Wrench,
  PackageOpen,
  LockOpen,
  GripVertical,
  Sparkles,
  Wand2,
  Instagram,
  Video,
  Twitter,
  Headphones,
  FileAudio,
  Link2,
  Binary,
  Palette,
  KeyRound,
  Regex,
  FileCode,
  ImageIcon,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { ToolCategory } from "@omnikit/shared";

/** Maps a tool's `icon` string (a Lucide name) to the component. */
export const iconMap: Record<string, LucideIcon> = {
  Image,
  Maximize2,
  Minimize2,
  Crop,
  RotateCw,
  RotateCcw,
  FlipHorizontal2,
  Contrast,
  Aperture,
  Stamp,
  Tags,
  SlidersHorizontal,
  Eraser,
  Files,
  Scissors,
  FileMinus,
  FileImage,
  ListOrdered,
  Droplets,
  FileText,
  Images,
  Download,
  Youtube,
  Music,
  QrCode,
  Braces,
  Hash,
  Wrench,
  PackageOpen,
  LockOpen,
  GripVertical,
  Sparkles,
  Wand2,
  Instagram,
  Video,
  Twitter,
  Headphones,
  FileAudio,
  Link2,
  Binary,
  Palette,
  KeyRound,
  Regex,
  FileCode,
};

export function getToolIcon(name: string): LucideIcon {
  return iconMap[name] ?? Wrench;
}

/** Per-category Lucide icon used for section headers, nav, palette groups. */
export const categoryIcon: Record<ToolCategory, LucideIcon> = {
  image: ImageIcon,
  pdf: FileText,
  download: Download,
  audio: Music,
  utility: Zap,
};
